# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'MXYSocketGCD' do
pod 'CocoaAsyncSocket','~> 7.5.0'
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for MXYSocketGCD

  target 'MXYSocketGCDTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MXYSocketGCDUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
